# Generated by Django 3.1.3 on 2020-11-09 03:19

from django.conf import settings
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0002_auto_20201109_0723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTagIndexPage',
            new_name='BlogTaglistingPage',
        ),
        migrations.AlterField(
            model_name='bloglistingpage',
            name='custom_title',
            field=wagtail.core.fields.RichTextField(help_text='Overwirtes the default title', max_length=100),
        ),
    ]
