# Generated by Django 3.1.3 on 2020-11-09 14:38

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201109_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='categories',
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('blockquote', wagtail.core.blocks.BlockQuoteBlock(label='Block Quote')), ('documentchooser', wagtail.documents.blocks.DocumentChooserBlock(label='Document Chooser')), ('url', wagtail.core.blocks.URLBlock(label='URL')), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Embed')), ('rawhtml', wagtail.core.blocks.RawHTMLBlock(label='Raw HTML')), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Table')), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(label='Markdown'))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
