# Generated by Django 3.1.3 on 2020-11-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201109_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='custom_title',
            field=models.CharField(default='Title', help_text='文章标题', max_length=80, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=models.CharField(help_text='文章简介', max_length=250),
        ),
    ]
