# Generated by Django 3.1.3 on 2020-11-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201109_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='caption',
        ),
    ]
