# Generated by Django 3.1.3 on 2020-11-09 16:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpagegalleryimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='custom_title',
            field=wagtail.core.fields.RichTextField(help_text='文章标题', max_length=80, verbose_name='Title'),
        ),
    ]
