# Generated by Django 3.1.3 on 2020-11-09 16:51

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201110_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='custom_title',
            field=models.CharField(help_text='文章标题', max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(help_text='文章简介', max_length=250),
        ),
    ]
