# Generated by Django 3.1.3 on 2020-11-09 17:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201110_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=ckeditor.fields.RichTextField(help_text='文章简介', max_length=250),
        ),
        migrations.AlterField(
            model_name='bloglistingpage',
            name='custom_title',
            field=ckeditor.fields.RichTextField(help_text='Overwirtes the default title', max_length=100),
        ),
    ]
