# Generated by Django 3.1.3 on 2020-11-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201110_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdetailpage',
            options={'ordering': ['-create_date']},
        ),
    ]
