# Generated by Django 3.1.3 on 2020-11-10 18:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_banner_cta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_cta',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_text',
            field=ckeditor.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
