# Generated by Django 3.1.3 on 2020-11-10 18:31

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201111_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_text',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
