# Generated by Django 3.1.3 on 2020-11-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201111_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
