# Generated by Django 3.1.3 on 2020-11-09 20:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('flex', '0004_auto_20201109_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flexpage',
            name='banner_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
