# Generated by Django 3.1.3 on 2020-11-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_auto_20201110_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='banner_subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
